### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by madnight** [lafreak/go-packet-server#1]
could you explain (in a few sentences) what this project is about and how it can be used (setup instructions)

**Comment by lafreak** [comment]
This is tcp server wrapped up in event-system in a package. It uses the same protocol as KalOnline (2 first bytes = packet length, third byte is packet ID, the rest is data). I will clean it up a little and make readme today with explainations and setup instructions. You can also check examples folder for now. :p

**Comment by madnight** [comment]
Very nice, if other people can import this package, it might be also be a good idea to choose a license for this project (such as MIT or GPL)

**Comment by lafreak** [comment]
Added readme, notify me if its enough please
